package net.liukrast.santa;

import net.neoforged.neoforge.common.ModConfigSpec;

public class SantaConfig {
    private SantaConfig() {}

    private static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();

    /* WORLDGEN */
    public static final ModConfigSpec.BooleanValue AUTOMATICALLY_PLACE_SANTA_BASE = BUILDER
            .comment("Defines whether santa's base should spawn automatically or should be placed by a player")
            .define("automaticallyPlaceSantaBase", true);

    /* SANTA DOCKS */
    public static final ModConfigSpec.IntValue MAX_DOCK_AMOUNT = BUILDER
            .comment("Defines the maximum amount of docks that can be placed direction the world")
            .defineInRange("maxDockAmount", 128, 0, 10000);
    public static final ModConfigSpec.IntValue MAX_PACKAGES_PER_DELIVERY = BUILDER
            .comment("Defines how many packages santa can extract/deliver when passing by a dock")
            .defineInRange("maxPackagesPerDelivery", 4, 0, Integer.MAX_VALUE);

    /* FROSTBURN */
    public static final ModConfigSpec.DoubleValue FROSTBURN_TEMPERATURE_INCREASE = BUILDER
            .comment("Every tick, temperature of a frostburn engine is increased by the overclock value multiplied by this")
            .defineInRange("frostburnTemperatureIncrease", 1, 0, Double.MAX_VALUE);

    public static final ModConfigSpec.IntValue FROSTBURN_EXPLODE_ON_BREAK = BUILDER
            .comment("Defines at how much temperature the frostburn engine will explode upon broken")
            .defineInRange("frostburnExplodeOnBreak", 5000, 0, Integer.MAX_VALUE);

    public static final ModConfigSpec.IntValue FROSTBURN_EXPLODE = BUILDER
            .comment("Defines at how much temperature the frostburn engine will explode by itself")
            .defineInRange("frostburnExplode", 10000, 0, Integer.MAX_VALUE);

    public static final ModConfigSpec.DoubleValue FROSTBURN_MULTIPLIER = BUILDER
            .comment("Multiplies the stress generated by a frostburn engine")
            .defineInRange("frostburnMultiplier", 16, 0, Double.MAX_VALUE);

    /* ROBO ELF */
    public static final ModConfigSpec.IntValue ELF_RECHARGE_PERCENTAGE = BUILDER
            .comment("Defines at what percentage of charge an elf starts looking for potential charge stations")
            .defineInRange("elfRechargePercentage", 50, 0, 100);
    public static final ModConfigSpec.IntValue ELF_UNSTRESS_COOLDOWN = BUILDER
            .comment("Defines how many ticks it takes for an elf to lower his stress by 1")
            .defineInRange("elfUnstressCooldown", 400, 0, Integer.MAX_VALUE);
    public static final ModConfigSpec.IntValue ELF_OVERSTRESS_PERCENTAGE = BUILDER
            .comment("Defines at what percentage an elf becomes overstressed")
            .defineInRange("elfOverstressPercentage", 70, 0, 100);

    public static final ModConfigSpec SPEC = BUILDER.build();
}
